### PR TITLE
Dataframe simulation

### PR DESCRIPTION
**Pull request by daikitag**
Simulate quantitative trait and effect size by using pandas dataframe.

### CODE REVIEW

**Comment by daikitag** [comment]
@jeromekelleher 
This is the new pull request that simulates quantitative trait and effect size by using a pandas dataframe. There are a lot of changes made in the files, so would it be possible for you to let me know if it is difficult to see the changes made in the files?

**Comment by daikitag** [comment]
I'm currently trying to add additional unit tests

**Comment by jeromekelleher** [comment]
Your history is a mess again here @daikitag - I'd recommend starting again from a fresh branch.

Always start a new PR by checking out your new feature branch from ``upstream/main``. It's nearly always a bad idea to ``git merge`` also under this development model (even though git unhelpfully suggests you do).

```
git fetch upstream
git checkout upstream/main
git checkout -b my-new-feature-branch
```

**Comment by daikitag** [comment]
Create a new pull request, https://github.com/tskit-dev/tstrait/pull/52

**Pull request closed without merging**
