### PR TITLE
Exact comparison

### PR DESCRIPTION
**Pull request by daikitag**
Conduct an exact test to compare the output of tstrait with other packages.

### CODE REVIEW

**Comment by gregorgorjanc** [comment]
@daikitag I don't know what exactly you run in AlphaSimR, but you might be interested in this aspect (since I know that simplePhenotypes works with input genotypes): https://github.com/HighlanderLab/jbancic_alphasimr_plants/blob/main/04_Techiques/importExternalHaplo.R

**Comment by daikitag** [comment]
@gregorgorjanc Thank you very much for your feedback. I transformed the tree sequence into an AlphaSimR founder population by adapting the codes from here (https://github.com/gaynorr/AlphaSimR_Examples/blob/master/misc/msprime.R), and then I extracted the simulated effect sizes and phenotypes from AlphaSimR by uding the following code: https://github.com/tskit-dev/tstrait/pull/137/files#diff-4da7360f4cf68a88124ec56e86d253d209994d3a47da37cfcbcd4ff941eb6d4bR84. I found the `importExternalHaplo.R` file to be interesting as well, and thank you for letting me know about it.

**Comment by gregorgorjanc** [comment]
> Thank you very much for your feedback. I transformed the tree sequence into an AlphaSimR founder population by adapting the codes from here (https://github.com/gaynorr/AlphaSimR_Examples/blob/master/misc/msprime.R),

That will work! All good then.

**Comment by jeromekelleher** [comment]
Looks great, but notebook format dosen't really add anything. We can encode these checks in validation.py so that they are run everytime, rather than just once.

**Comment by daikitag** [comment]
The codes in this pull request are used in https://github.com/tskit-dev/tstrait/pull/140

**Pull request closed without merging**
