### PR TITLE
CODE: num_causal error

### PR DESCRIPTION
**Pull request by daikitag**
Detect num_causal error in sim_trait function

### CODE REVIEW

**Comment by daikitag** [comment]
This is resolving https://github.com/tskit-dev/tstrait/issues/94

**Comment by GertjanBisschop** [comment]
LGTM. Shall we do the same for the `random_seed` variable?

**Comment by daikitag** [comment]
For the `random_seed` variable, `np.random.default_rng` function https://numpy.org/doc/stable/reference/random/generator.html can have more inputs than integers, and I received a suggestion from Jerome saying that we shouldn't be trying to generate errors for that part.

**Comment by daikitag** [comment]
Thank you for your prompt feedback @GertjanBisschop

**Comment by GertjanBisschop** [comment]
cool!

**Review by GertjanBisschop — APPROVED** [review]

**Pull request merged**
