### PR TITLE
CODE: New API

### PR DESCRIPTION
**Pull request by daikitag**
New tstrait API

### CODE REVIEW

**Comment by daikitag** [comment]
This will fail, as I haven't written the tests for new functions, but I just wanted to make a PR at first to receive some feedback.

**Comment by daikitag** [comment]
The pytest is failing because of the name error (genetic_value.py and `genetic_value` function), and I will modify it afterwards.

**Comment by daikitag** [comment]
I hope the suggestions made here resolves https://github.com/tskit-dev/tstrait/issues/103

**Comment by jeromekelleher** [comment]
I really do think we should write things as simply and cleanly as we can first, and optimise for performance in the nonzero alpha case later.

Duplicating code is a bad idea, and you should only do it when there's a compelling reason. I've not seen a compelling reason, particularly when we're actually doing unnecessary work at the moment for alpha of zero (which I assume is a common case).

**Comment by daikitag** [comment]
Closed due to updates in https://github.com/tskit-dev/tstrait/pull/111 and https://github.com/tskit-dev/tstrait/pull/112

**Pull request closed without merging**
