### PR TITLE
Causal site

### PR DESCRIPTION
**Pull request by daikitag**
Add `site_id` input in effect size simulation, so that the users can define which site IDs to include in the simulation.

### CODE REVIEW

**Comment by daikitag** [comment]
This code deals with the issue https://github.com/tskit-dev/tstrait/issues/53, and allows users to input site IDs of their choice.

**Comment by GertjanBisschop** [comment]
I think that `num_causal` and `site_id` can be squashed into a single flag: `causal_sites` that is either an integer or a list/array. (see conclusion #53) This will definitely reduce confusion. Either you specify the exact site_ids, or `causal_sites` sites get randomly picked. I feel like people might otherwise think we support the option to randomly pick sites from a provided subset.

Also, feel free to suggest other names for the single flag. Just a suggestion.

**Comment by daikitag** [comment]
Thank you for your prompt feedback. I just incorporated those changes inside the function. I think the code is looking clearer now.

**Comment by jeromekelleher** [comment]
I like the idea, but we should think about how this interacts with simulating multiple traits (#54). Here's what the proposal is over there:
```python
num_traits = 100
# Choose number of causal sites uniformly for each trait
num_causal = np.random.uniform(10, 100, size=num_traits)
df_traits = tstrait.sim_traits(ts, num_causal=num_causal)
```

We could do choosing specific sites with something like
```python
num_traits = 100
causal_sites = []
for _ in range(num_traits):
     num_sites = np.random.uniform(10, 100)
     random_sites = np.random.choice(np.arange(ts.num_sites), num_sites)
     causal_sites.append(random_sites)
df_traits = tstrait.sim_traits(ts, causal_sites=causal_sites)
```

In this context it's unhelpful wrapping together the ``num_causal`` and ``causal_sites`` arguments because we want to interpret the first dimension as "number of traits". We could see the ``num_causal`` argument as a (mutually exclusive) shorthand for the ``causal_sites`` argument given here?

**Comment by daikitag** [comment]
I have incorporated the multiple trait simulation in https://github.com/tskit-dev/tstrait/pull/56. With this modification, I think it is safe to implement this code to select causal sites. I would appreciate any suggestions from you.

**Comment by jeromekelleher** [comment]
@daikitag probably best to close this now? 

Or should we update?

**Comment by daikitag** [comment]
@jeromekelleher 
The code architecture is different as before, so I think it is good that we close this issue now. I will work on improving this in the future.

**Pull request closed without merging**
