### PR TITLE
Test

### PR DESCRIPTION
**Pull request by daikitag**
Update tests and warnings in tstrait

### CODE REVIEW

**Review by jeromekelleher — COMMENTED** [review]
Abstracting out the necessary type checking for parameters is good, and makes the code more readable.

I think you're going a bit overboard though. There are really only two reasons why we'd want to catching parameter type and range errors:

1. A clearly nonsensical input value is accepted and silently gives nonsensical output
2. A nonsensical input is results in a hard-to-understand error message.

If the result of providing a nonsensical input (like say, a string to a function that expects an integer) is a ValueError saying you can't convert a string to an integer, then that's totally fine, and in fact better than us trying to trap this error and raise a custom error message.

**Comment by daikitag** [comment]
Thank you Jerome for your valuable feedback, and I really appreciate it, as I wouldn't have been able to learn these things without your support.
I only conducted error tests for inputs that are only used in `tstrait`, and I removed all error detection messages for inputs that use functions from other packages like `numpy`. Would it be possible for you to check it whenever you have some time?

**Comment by jeromekelleher** [comment]
Looks good, just needs a rebase and squash I think

**Comment by daikitag** [comment]
> Looks good, just needs a rebase and squash I think

I created a new pull request with the same changes, and would it be possible for you to merge that pull request? Unfortunately, I was not able to rebase this branch.
https://github.com/tskit-dev/tstrait/pull/61

**Pull request closed without merging**
