### PR TITLE
DOC: Build documentation

### PR DESCRIPTION
**Pull request by daikitag**
Initialize documentation.
https://github.com/tskit-dev/tstrait/pull/77 must be processed before merging the pull request.

### CODE REVIEW

**Comment by daikitag** [comment]
Note:
The documentation and docstrings are finalized after this pull request. After modifying the doc CI, I think we are ready to put the documentation to tskit.dev and releasing the package.

**Comment by jeromekelleher** [comment]
Looks good @daikitag, can you rebase to drop the first commit please?

**Comment by jeromekelleher** [comment]
The build is still failing because of a handful of warnings:
```
/home/runner/work/tstrait/tstrait/docs/_api/tstrait.GeneticResult.rst:27:<autosummary>:1: WARNING: py:obj reference target not found: tstrait.GeneticResult.effect_size
113
writing output... [100%] release/index                                         
114
/home/runner/work/tstrait/tstrait/docs/_api/tstrait.GeneticResult.rst:27:<autosummary>:1: WARNING: py:obj reference target not found: tstrait.GeneticResult.genetic
115
/home/runner/work/tstrait/tstrait/docs/_api/tstrait.PhenotypeResult.rst:27:<autosummary>:1: WARNING: py:obj reference target not found: tstrait.PhenotypeResult.effect_size
116
/home/runner/work/tstrait/tstrait/docs/_api/tstrait.PhenotypeResult.rst:27:<autosummary>:1: WARNING: py:obj reference target not found: tstrait.PhenotypeResult.phenotype
```
We should fix those (usually there's some workarounds about ignoring particular objects)

**Comment by daikitag** [comment]
I tried to remove the error message, but it seems that there is an issue behind using numpy style docstring in jupyter book https://github.com/executablebooks/sphinx-book-theme/issues/729
Thus, I just decided to suppress warnings caused by `ref`.

I hope it is working well now.

**Pull request merged**
